### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by rossbulat** [thecodehunter/react-native-activity-rings#1]
This is a neat idea, but I am getting the following error when following the basic setup outlined in the docs:

![Simulator Screen Shot - iPhone 11 - 2020-07-20 at 23 52 36](https://user-images.githubusercontent.com/13929023/87964322-3e039d80-cae4-11ea-8c8f-7df74927b565.png)

**Comment by thecodehunter** [comment]
Hi, i would need more context in order to help you.

React Native version, NodeJS version, Typescript or JS ?, Expo ?

Thank you!

**Comment by rossbulat** [comment]
Hi @thecodehunter, sure thing, here are the details:

Platform: MacOS 10.15.6
React Native version: v14.3.0
**Expo:  37.0.8** (bare bones project)
**TypeScript: 3.8.3**

**Comment by rossbulat** [comment]
@thecodehunter Are you available on Gitter / Slack / anywhere else to discuss this?

**Comment by thecodehunter** [comment]
Ross i would follow up with you via Email with some details.

**Comment by thecodehunter** [comment]
I published a new version that exports JS files instead of JSX , let me know if webpack is grabbing the files now.

**Comment by rossbulat** [comment]
Nice, I am now receiving another error, again with the basic example:

<img width="372" alt="Screenshot 2020-07-26 at 13 23 53" src="https://user-images.githubusercontent.com/13929023/88473006-64419700-cf43-11ea-833d-d67051f4e0f7.png">

**Comment by thecodehunter** [comment]
Seems like an issue with having 2 versions of react-native-svg colliding, activity-rings has a dependency on react-native-svg, try deleting lock and do a fresh yarn install, check this out that might help you: https://github.com/react-native-community/react-native-svg/issues/591.

UPDATE: For what i read and verified, Expo already includes react-native-svg library , i will change the dependency to be a peerDependency and do some testing, will update it soon, thanks for your patience.

**Comment by thecodehunter** [comment]
Fixed on 1.1.2 please update and let me know. 

Thank you!
